<a href="https://colab.research.google.com/github/Sarah-Siu/BreastCancerAnaylsis/blob/main/Sarah_ML_Models_PT2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "data.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "uciml/breast-cancer-wisconsin-data",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

Using Colab cache for faster access to the 'breast-cancer-wisconsin-data' dataset.
First 5 records:          id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0
1    842517         M        20.57         17.77          132.90     1326.0
2  84300903         M        19.69         21.25          130.00     1203.0
3  84348301         M        11.42         20.38           77.58      386.1
4  84358402         M        20.29         14.34          135.10     1297.0

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710
1          0.08474           0.07864          0.0869              0.07017
2          0.10960           0.15990          0.1974              0.12790
3          0.14250           0.28390          0.2414              0.10520
4          0.10030           0.13280          0.1980              0.10430

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622
1  ...          23.41           158.80      1956.0            0.1238
2  ...          25.53           152.50      1709.0            0.1444
3  ...          26.50            98.87       567.7            0.2098
4  ...          16.67           152.20      1575.0            0.1374

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601
1             0.1866           0.2416                0.1860          0.2750
2             0.4245           0.4504                0.2430          0.3613
3             0.8663           0.6869                0.2575          0.6638
4             0.2050           0.4000                0.1625          0.2364

   fractal_dimension_worst  Unnamed: 32
0                  0.11890          NaN
1                  0.08902          NaN
2                  0.08758          NaN
3                  0.17300          NaN
4                  0.07678          NaN

[5 rows x 33 columns]

In [ ]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
d ={'M':1,'B':0} #M - Malignant B - Benign
df['diagnosis'] = df['diagnosis'].replace(d, inplace=False).astype('int64')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,1,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,1,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,1,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,1,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
import numpy as np
import pandas as pd
import torch

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

import warnings
warnings.filterwarnings('ignore')

In [ ]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [ ]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,1,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,1,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,1,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,1,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    df.iloc[:, 1:],
    df.iloc[:, 0],
    test_size=0.2
)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[ 3.11262315,  1.35890237,  3.24656796, ...,  2.63862544,
        -0.8563375 ,  1.18866841],
       [ 1.60903377,  0.25781753,  1.56577995, ...,  0.71630264,
        -0.54204111,  0.42606404],
       [-0.37130347, -0.70119185, -0.40689125, ..., -0.87030349,
         1.16714804, -0.72505785],
       ...,
       [ 0.12801233, -0.54964469,  0.07807758, ..., -0.55635476,
        -0.69432905, -0.9836995 ],
       [-1.15836057, -0.96166353, -1.17021498, ..., -1.59661651,
         0.08007134, -0.37261696],
       [-0.1907599 , -0.06658812, -0.17240083, ...,  0.4710302 ,
        -0.35249122, -0.37872224]])

In [ ]:
y_train

82     1
517    1
268    0
385    1
415    0
      ..
57     1
339    1
486    0
185    0
396    0
Name: diagnosis, Length: 455, dtype: int64

In [ ]:
encoder = LabelEncoder()
# Convert both to a string to ensure consistency
y_train = encoder.fit_transform(y_train.astype(str))
y_test = encoder.transform(y_test.astype(str))

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

In [ ]:
class SimpleNN():

    def __init__(self, X):

        self.weights = torch.rand(X.shape[1], dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)

        return y_pred

    def loss_function(self, y_pred, y):

        # Clamp preditions to avoid log(0)
        epsilon = 1e-7

        # manually calculate the loss function
        y_pred = torch.clamp( y_pred, epsilon, 1 - epsilon)
        loss = - (y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()

        return loss

In [ ]:
LR = 0.1
EPOCHS = 50

In [ ]:
# create model
model = SimpleNN(X_train_tensor)

# define loop
for epoch in range(EPOCHS):

    # forward pass
    y_pred = model.forward(X_train_tensor)

    # loss calculate
    loss = model.loss_function(y_pred, y_train_tensor)

    # backward pass
    loss.backward()

    # parameters update
    with torch.no_grad():
        model.weights -= LR * model.weights.grad
        model.bias -= LR * model.bias.grad

    # Zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    print(f"Epoch: {epoch + 1} | Loss: {loss.item()} ")

Epoch: 1 | Loss: 0.3082039907468619
Epoch: 2 | Loss: 0.3037123420363713
Epoch: 3 | Loss: 0.29935688226469187
Epoch: 4 | Loss: 0.29513408308065897
Epoch: 5 | Loss: 0.2910403381722024
Epoch: 6 | Loss: 0.28707195119568973
Epoch: 7 | Loss: 0.28322512962362034
Epoch: 8 | Loss: 0.2794959861680512
Epoch: 9 | Loss: 0.27588054880372287
Epoch: 10 | Loss: 0.27237477841239854
Epoch: 11 | Loss: 0.268974592827891
Epoch: 12 | Loss: 0.2656758951676313
Epoch: 13 | Loss: 0.2624746041411006
Epoch: 14 | Loss: 0.2593666841212498
Epoch: 15 | Loss: 0.25634817311891683
Epoch: 16 | Loss: 0.2534152073528356
Epoch: 17 | Loss: 0.25056404137117394
Epoch: 18 | Loss: 0.2477910638956466
Epoch: 19 | Loss: 0.24509280904258673
Epoch: 20 | Loss: 0.24246596355591968
Epoch: 21 | Loss: 0.23990737058903755
Epoch: 22 | Loss: 0.23741403068726147
Epoch: 23 | Loss: 0.23498310061448882
Epoch: 24 | Loss: 0.23261189060877208
Epoch: 25 | Loss: 0.2301369665680413
Epoch: 26 | Loss: 0.22657500363570698
Epoch: 27 | Loss: 0.22309436644998637
Epoch: 28 | Loss: 0.2196916168974506
Epoch: 29 | Loss: 0.21636355891342926
Epoch: 30 | Loss: 0.21310723352129712
Epoch: 31 | Loss: 0.2099199137783535
Epoch: 32 | Loss: 0.20679909951435677
Epoch: 33 | Loss: 0.20374251168940338
Epoch: 34 | Loss: 0.20074808616093304
Epoch: 35 | Loss: 0.19781396662547868
Epoch: 36 | Loss: 0.1949384964648576
Epoch: 37 | Loss: 0.19212020925125337
Epoch: 38 | Loss: 0.18935781764691453
Epoch: 39 | Loss: 0.18665020048239483
Epoch: 40 | Loss: 0.18399638783059824
Epoch: 41 | Loss: 0.18139554397988958
Epoch: 42 | Loss: 0.17884694831870585
Epoch: 43 | Loss: 0.17634997428659585
Epoch: 44 | Loss: 0.1739040667311715
Epoch: 45 | Loss: 0.1715087182094031
Epoch: 46 | Loss: 0.16916344472839007
Epoch: 47 | Loss: 0.16686776228502886
Epoch: 48 | Loss: 0.16462116466344956
Epoch: 49 | Loss: 0.16242310376405963
Epoch: 50 | Loss: 0.16027297336406157

In [ ]:
model.bias

tensor([-0.0684], dtype=torch.float64, requires_grad=True)

In [ ]:
model.weights

tensor([ 0.5037,  1.0213,  0.9183,  0.4610,  0.0253, -0.1388,  0.8670,  0.3129,
        -0.0588, -0.2217,  0.1606,  0.1241,  0.8977,  0.0667,  0.3110,  0.5815,
         0.0740,  0.0200,  0.3534,  0.3457,  1.0003,  0.4080,  0.6646,  0.8382,
         0.1971,  0.2101,  0.8590,  0.4424,  0.9418, -0.1080],
       dtype=torch.float64, requires_grad=True)

In [ ]:
# Model evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()

    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.9385964870452881